name: movie_app
version: 1.0.0+1
publish_to: none
description: An Android app to book a ticket for your favorite movies.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
