name: tes_kerja
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
